### ISSUE TITLE
Improper raw name for Jensen's

### ISSUE THREAD

**Issue by steelskillet** [fantinodavide/SquadLayerList#1]
Jensen's Training layers have the improper raw name. currently they are `JensensRange_Training_<team1>-<team2>` and they should be `JensensRange_<team1>-<team2>`.

**Comment by fantinodavide** [comment]
@steelskillet fixed with [this commit](https://github.com/fantinodavide/SquadLayerList/commit/dfee84b74342bc830f8f8f6a186f66251d96b731)
thank you very much!
